const STATE_NAMES = {
  MAIN: 'MAIN',

  LOG_QUERY_CATEGORY: 'LOG_QUERY_CATEGORY',
  DEVICE_FAULTY_CATEGORY: 'DEVICE_FAULTY_CATEGORY',
  LOG_QUERY_MERCHANT_ID: 'LOG_QUERY_MERCHANT_ID',
  LOG_QUERY_OTHER_DETAILS: 'LOG_QUERY_OTHER_DETAILS',
  LOG_QUERY_CONTACT: 'LOG_QUERY_CONTACT',

  LOG_COMPLAINT_DETAILS: 'LOG_COMPLAINT_DETAILS',
  LOG_COMPLAINT_MERCHANT_ID: 'LOG_COMPLAINT_MERCHANT_ID',
  LOG_COMPLAINT_CONTACT: 'LOG_COMPLAINT_CONTACT',

  SPEEDPOINT_CATEGORY: 'SPEEDPOINT_CATEGORY',
  SPEEDPOINT_MERCHANT_ID: 'SPEEDPOINT_MERCHANT_ID',
  SPEEDPOINT_TERMINAL_ID: 'SPEEDPOINT_TERMINAL_ID',
  SPEEDPOINT_CONTACT: 'SPEEDPOINT_CONTACT',

  TRACK_QUERY_LIST: 'TRACK_QUERY_LIST',
};

// No flow in this app currently collects a secret (PIN, OTP, etc.). This set
// stays wired into controller.js's log redaction so a future flow that does
// only needs to add its state name here, not touch the logging code.
const SENSITIVE = new Set([]);

module.exports = { ...STATE_NAMES, SENSITIVE };
